Bill_2_split/Bill_2_split/urls.py
from django.urls import path
from Bill_2_split import views
from django.views.generic import TemplateView

app_name = 'Bill_2_pay'

placeholder_view = TemplateView.as_view(template_name='Bill_2_split/placeholder.html')

urlpatterns = [
    path('',
         views.IndexView.as_view(),
         name='IndexView'),

    path('user/',
         views.UserView.as_view(),
         name='UserView'),

    path('list_of_ledgers/<int:user_pk>/',
         views.ListOfLedgersView.as_view(),
         name='ListOfLedgersView'),

    path('list_of_ledgers/<int:user_pk>/add/',
         views.LedgerAddView.as_view(),
         name='LedgerAddView'),

    path('ledger_detail/<int:ledger_pk>/<int:user_pk>/',
         views.LedgerDetailView.as_view(),
         name='LedgerDetailView'),

    path('ledger_detail/<int:ledger_pk>/<int:user_pk>/edit/',
         views.LedgerEditView.as_view(),
         name='LedgerEditView'),

    path('ledger_detail/<int:ledger_pk>/<int:user_pk>/add/',
         views.PaymentAddView.as_view(),
         name='PaymentAddView'),

    path('payment_detail/<int:payment_pk>/<int:ledger_pk>/<int:user_pk>/',
         views.PaymentDetailView.as_view(),
         name='PaymentDetailView'),

    path('payment_detail/<int:payment_pk>/<int:ledger_pk>/<int:user_pk>/edit/',
         views.PaymentEditView.as_view(),
         name='PaymentEditView'),

    path('payment_detail/<int:payment_pk>/<int:ledger_pk>/<int:user_pk>/delete/',
         views.PaymentDeleteView.as_view(),
         name='PaymentDeleteView'),

    path('relation_detail/<int:payment_pk>/<int:ledger_pk>/<int:user_pk>/add/',
         views.RelationsAddView.as_view(),
         name='RelationsAddView'),

    path('relation_detail/<int:payment_pk>/<int:ledger_pk>/<int:user_pk>/edit/',
         views.RelationsEditView.as_view(),
         name='RelationsEditView'),

]

Bill_2_split/_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('Bill_2_split.urls', namespace='Bill_2_split')), #adds prefix bill_2_split:index
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    from debug_toolbar.toolbar import debug_toolbar_urls
    urlpatterns.extend(debug_toolbar_urls())

Bill_2_split/Bill_2_split/models.py
from django.db import models
from datetime import datetime
from django.utils.text import slugify
from django.shortcuts import reverse


class AbstractBase(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, blank=True)
    desc = models.CharField(max_length=2000, blank=True)

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        if not self.slug and self.name:
            self.slug = slugify(self.name + self.pk)
        super().save(*args, **kwargs)

    def save(self, *args, **kwargs):
        if not self.slug and self.name:
            # Uložení slug až po vytvoření primárního klíče
            super().save(*args, **kwargs)
            self.slug = slugify(self.name + str(self.pk))
            super().save(update_fields=['slug'])
        else:
            super().save(*args, **kwargs)

    def __str__(self):
        return self.name

class User(AbstractBase):
    email = models.CharField(max_length=50, blank=True)
    password = models.CharField(max_length=50, blank=True)
    # If no e-mail and password => user does not have an account yet, but can be established

class Ledger(AbstractBase):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    # meaning of user - is the owner of the Ledger, can edit it
    def get_absolute_url(self):
        return reverse('Bill_2_split:ListOfLedgersView', kwargs={'user_pk': self.user.pk})


class Payment(AbstractBase):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    ledger = models.ForeignKey(Ledger, on_delete=models.PROTECT)
    entry_time = models.DateTimeField(default=datetime.now)
    cost = models.DecimalField(max_digits=10, decimal_places=2)
    payment_time = models.DateTimeField(default=datetime.now)
    # meaning of user - is the owner of the entry, can edit it

    def get_absolute_url(self):
        return reverse('Bill_2_split:PaymentDetailView', kwargs={'slug': self.slug})


class Relation(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    payment = models.ForeignKey(Payment, on_delete=models.PROTECT)
    relation = models.DecimalField(max_digits=10, decimal_places=3)

Bill_2_split/Bill_2_split/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from .models import Payment, Relation

class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ['name', 'cost', 'desc']
        widgets = {
            'desc': forms.Textarea(attrs={'rows': 3, 'placeholder': 'Description'}),
        }

class RelationForm(forms.ModelForm):
    class Meta:
        model = Relation
        fields = ['user', 'relation']
        widgets = {
            'relation': forms.NumberInput(attrs={'placeholder': 'Relation Value'}),
        }


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        label='Username',
        widget=forms.TextInput(attrs={'placeholder': 'Username'}),
    )
    password = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(attrs={'placeholder': 'Password'}),
    )

Bill_2_split/Bill_2_split/views.py
from django.views import generic, View
from Bill_2_split.models import User, Ledger, Payment, Relation
from .functions import calculate_relation_costs
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from datetime import datetime
from .forms import RelationForm
from django.shortcuts import redirect, get_object_or_404
from django.views.generic.edit import UpdateView, DeleteView

class IndexView(generic.TemplateView):
    template_name = 'Bill_2_split/index.html'
    title = 'Welcome page'

class UserView(generic.TemplateView):
    template_name = 'Bill_2_split/user.html'
    title = 'User page'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['users'] = User.objects.all()
        return context

class ListOfLedgersView(generic.TemplateView):
    template_name = 'Bill_2_split/list_of_ledgers.html'
    title = 'List of ledgers'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_id = self.kwargs.get('user_pk')
        user = User.objects.get(pk=user_id)  # získej uživatele podle pk
        context['user'] = user
        context['ledgers'] = Ledger.objects.filter(payment__relation__user=user).distinct()  # vyfiltruj ledgery pro daného uživatele
        return context

class LedgerAddView(generic.CreateView):
    model = Ledger
    template_name = 'Bill_2_split/ledger_add.html'
    fields = ['name', 'desc']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_id = self.kwargs.get('user_pk')  # Získání ID uživatele z URL
        context['user'] = User.objects.get(pk=user_id)  # Přidání uživatele do kontextu
        return context

    def form_valid(self, form):
        # Získej ID uživatele z URL
        user_id = self.kwargs.get('user_pk')
        user = User.objects.get(pk=user_id)

        # Ulož prázdný ledger
        form.instance.user = user
        response = super().form_valid(form)
        ledger = form.instance

        # Zkontroluj, zda již payment neexistuje
        payment, created = Payment.objects.get_or_create(
            ledger=ledger,
            cost=0,
            user=user,
            defaults={
                'name': 'ledger_created',
                'desc': 'dummy_payment',
                'entry_time': datetime.now(),
                'payment_time': datetime.now(),
            }
        )

        # Vytvoř dummy relation pro uživatele
        Relation.objects.get_or_create(
            user=user,
            payment=payment,
            defaults={
                'relation': 1
            }
        )

        return HttpResponseRedirect(reverse('Bill_2_pay:ListOfLedgersView', kwargs={'user_pk': user.pk}))


class LedgerDetailView(generic.DetailView):
    model = Ledger
    template_name = 'Bill_2_split/ledger_detail.html'
    title = 'Ledger detail'

    def get_object(self):
        ledger_pk = self.kwargs.get('ledger_pk')
        return Ledger.objects.get(pk=ledger_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        ledger = self.get_object()
        user_id = self.kwargs.get('user_pk')
        user = User.objects.get(pk=user_id)

        # Retrieve payments and relations for the ledger
        payments = Payment.objects.filter(ledger=ledger)
        relations = Relation.objects.filter(payment__in=payments)

        # Get users associated with the ledger through relations
        ledger_users = User.objects.filter(relation__in=relations).distinct()

        # Calculate balance for each user
        user_balances = []
        for user in ledger_users:
            # Get all relations for this user and ledger
            user_relations = relations.filter(user=user)

            # Calculate the total balance for this user
            balance = sum(
                payment.cost * relation.relation
                for payment in payments
                for relation in user_relations
                if relation.payment == payment
            )

            # Format the balance
            balance_str = f"{user.name}: {balance:+.2f}"
            user_balances.append(balance_str)

            # Debug print statement
            print(f'User: {user.name}, Balance: {balance}')

        # Adding context
        context['relations'] = relations
        context['ledger'] = ledger
        context['ledger_users'] = ledger_users
        context['payments'] = payments
        context['user'] = user
        context['user_balances'] = user_balances

        return context




class LedgerEditView(UpdateView):
    model = Ledger
    template_name = 'Bill_2_split/ledger_edit.html'
    fields = ['name', 'desc']
    context_object_name = 'ledger'

    def get_object(self, queryset=None):
        ledger_pk = self.kwargs.get('ledger_pk')
        return get_object_or_404(Ledger, pk=ledger_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_id = self.kwargs.get('user_pk')
        context['user'] = get_object_or_404(User, pk=user_id)
        return context

    def form_valid(self, form):
        user_id = self.kwargs.get('user_pk')
        user = get_object_or_404(User, pk=user_id)
        form.instance.user = user
        return super().form_valid(form)

    def get_success_url(self):
        ledger = self.object
        user_id = self.kwargs.get('user_pk')
        return reverse('Bill_2_split:LedgerDetailView', kwargs={'ledger_pk': ledger.pk, 'user_pk': user_id})

class PaymentAddView(generic.CreateView):
    model = Payment
    template_name = 'Bill_2_split/payment_add.html'
    fields = ['name', 'cost', 'desc']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        ledger_id = self.kwargs.get('ledger_pk')
        user_id = self.kwargs.get('user_pk')

        ledger = Ledger.objects.get(pk=ledger_id)
        user = User.objects.get(pk=user_id)

        context['ledger'] = ledger
        context['user'] = user
        return context

    def form_valid(self, form):
        ledger_id = self.kwargs.get('ledger_pk')
        user_id = self.kwargs.get('user_pk')
        ledger = Ledger.objects.get(pk=ledger_id)
        user = User.objects.get(pk=user_id)

        form.instance.ledger = ledger
        form.instance.user = user
        relation_value = self.request.POST.get('relation', '0')
        if int(relation_value) != 0:                                # Udělej zápis jen pro relatiok které má smysl - ne všechny uživatele
            Relation.objects.create(user=user, ledger=ledger, relation=int(relation_value))

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('Bill_2_pay:RelationsAddView', kwargs={
            'payment_pk': self.object.pk,
            'ledger_pk': self.object.ledger.pk,
            'user_pk': self.object.user.pk})

class PaymentDetailView(generic.DetailView):
    model = Payment
    template_name = 'Bill_2_split/payment_detail.html'
    title = 'Payment detail'

    def get_object(self):
        payment_pk = self.kwargs.get('payment_pk')
        return Payment.objects.get(pk=payment_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        payment = self.get_object()

        user_id = self.kwargs.get('user_pk')
        user = User.objects.get(pk=user_id)

        ledger_id = self.kwargs.get('ledger_pk')
        ledger = Ledger.objects.get(pk=ledger_id)

        relations = Relation.objects.filter(payment=payment)

        balance_change = calculate_relation_costs(relations, payment.cost)

        context['ledger'] = ledger
        context['user'] = user
        context['payment'] = payment
        context['relations'] = relations
        context['balance_change'] = balance_change

        return context

class PaymentEditView(UpdateView):
    model = Payment
    template_name = 'Bill_2_split/payment_edit.html'
    fields = ['name', 'cost', 'desc']

    def get_object(self, queryset=None):
        payment_pk = self.kwargs.get('payment_pk')
        return get_object_or_404(Payment, pk=payment_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_id = self.kwargs.get('user_pk')
        context['user'] = get_object_or_404(User, pk=user_id)
        context['ledger'] = self.object.ledger
        return context

    def form_valid(self, form):
        user_id = self.kwargs.get('user_pk')
        user = get_object_or_404(User, pk=user_id)
        form.instance.user = user
        return super().form_valid(form)

    def get_success_url(self):
        ledger = self.object.ledger
        user_id = self.kwargs.get('user_pk')
        return reverse('Bill_2_split:RelationsEditView', kwargs={
                           'payment_pk': self.object.pk,
                           'ledger_pk': ledger.pk,
                           'user_pk': user_id
        })

#
class PaymentDeleteView(View):

    def post(self, request, *args, **kwargs):
        payment_pk = self.kwargs.get('payment_pk')
        ledger_pk = self.kwargs.get('ledger_pk')
        user_pk = self.kwargs.get('user_pk')

        payment = get_object_or_404(Payment, pk=payment_pk)
        # Smažte všechny vztahy související s tímto platbou
        Relation.objects.filter(payment=payment).delete()
        # Smažte samotnou platbu
        payment.delete()

        # Přesměrování zpět na detail ledgeru
        return redirect('Bill_2_split:LedgerDetailView', ledger_pk=ledger_pk, user_pk=user_pk)

#

class RelationsAddView(generic.DetailView):
    model = Payment
    template_name = 'Bill_2_split/relation_add.html'
    context_object_name = 'payment'

    def get_object(self):
        payment_id = self.kwargs.get('payment_pk')
        return Payment.objects.get(pk=payment_id)

    def get_context_data(self, **kwargs):

Bill_2_split/Bill_2_split/templates/Bill_2_split/index.html
{% extends 'Bill_2_split/_base.html' %}

{% block Bill_2_split_content %}
{% load static %}

<nav id="horni-nav">
    <ul>
        <li><a href="{% url 'Bill_2_split:IndexView' %}">
            <img src="{% static 'Bill_2_split/icons/home_page.png' %}"><span>You are here</span></a></li>
        <li><a href="{% url 'Bill_2_split:UserView' %}">
            <img src="{% static 'Bill_2_split/icons/user.png' %}"><span>Start here</span></a></li>
        <li><a href=""><img src="{% static 'Bill_2_split/icons/bw_ledgers.png' %}"></a></li>
        <li><a href=""><img src="{% static 'Bill_2_split/icons/bw_ledger.png' %}"></a></li>
        <li><a href=""><img src="{% static 'Bill_2_split/icons/bw_glass.png' %}"></a></li>
    </ul>
</nav>

<section>
  <header>
    <h1>Bill 2 Split</h1>
      <h3>Simple Expense Sharing</h3>
    <p>Welcome to Bill 2 Split, the app that simplifies managing shared expenses and dividing costs among multiple users.
    This app helps you efficiently track payments, keep records of transactions, and manage relationships between friends, family, or colleagues.</p>
  </header>


    <h2>Purpose of the App</h2>
    <p>Bill 2 Split is designed for anyone who needs a simple way to track shared expenses. Whether it's for a group trip, household budget, or work-related costs,
    this app allows you to easily create payments, add users, and keep track of who owes what.</p>

    <h2>Main Features</h2>
    <ul>
      <li>Payment and expense distribution management</li>
      <li>Creating and tracking payments</li>
      <li>Overview of cost-sharing between users</li>
      <li>Quick and easy addition of payments</li>
    </ul>


  <footer>
    <p><strong>Start Today!</strong> Sign up and begin tracking your expenses with Bill 2 Split.</p>
  </footer>
</section>

{% endblock %}

Bill_2_split/Bill_2_split/templates/Bill_2_split/ledger_add.html
{% extends 'Bill_2_split/_base.html' %}

{% block Bill_2_split_content %}
{% load static %}

<nav id="horni-nav">
    <ul><li><a href="{% url 'Bill_2_split:IndexView' %}">
            <img src="{% static 'Bill_2_split/icons/home_page.png' %}"><span>Homepage</span></a></li>
        <li><a href="{% url 'Bill_2_split:UserView' %}">
            <img src="{% static 'Bill_2_split/icons/user.png' %}"><span>User selection</span></a></li>
        <li><a href="{% url 'Bill_2_split:ListOfLedgersView' user.pk %}">
            <img src="{% static 'Bill_2_split/icons/ledgers.png' %}"><span>You are here</span></a></li>
        <li><a href=""><img src="{% static 'Bill_2_split/icons/bw_ledger.png' %}"></a></li>
        <li><a href=""><img src="{% static 'Bill_2_split/icons/bw_glass.png' %}"></a></li>
    </ul>
</nav>

<h1>Add new ledger</h1>
    <form action="{% url 'Bill_2_split:LedgerAddView' user_pk=user.pk %}" method="POST">

        {% csrf_token %}

        {{ form }}

        <button type="submit">Create new ledger</button>
    </form>


{% endblock %}

Bill_2_split/Bill_2_split/templates/Bill_2_split/ledger_detail.html
{% extends 'Bill_2_split/_base.html' %}

{% block Bill_2_split_content %}
{% load static %}

<nav id="horni-nav">
    <ul>
        <li><a href="{% url 'Bill_2_split:IndexView' %}">
            <img src="{% static 'Bill_2_split/icons/home_page.png' %}"><span>Homepage</span></a></li>
        <li><a href="{% url 'Bill_2_split:UserView' %}">
            <img src="{% static 'Bill_2_split/icons/user.png' %}"><span>User selection</span></a></li>
        <li><a href="{% url 'Bill_2_split:ListOfLedgersView' user.pk %}">
            <img src="{% static 'Bill_2_split/icons/ledgers.png' %}"><span>Ledgers overview</span></a></li>
        <li><a href="{% url 'Bill_2_split:LedgerDetailView' ledger.pk user.pk %}">
            <img src="{% static 'Bill_2_split/icons/ledger.png' %}"><span>You are here</span></a></li>
        <li><a href=""><img src="{% static 'Bill_2_split/icons/bw_glass.png' %}"></a></li>
    </ul>
</nav>

<h1>
    {{ ledger.name }}
</h1>

<p> {{ ledger.desc }}</p>
<p></p>
<p></p>

<h2>Users associated with this ledger and their balance:</h2>
<ul>
    {% for user_balance in user_balances %}
    <li>{{ user_balance }}</li>
    {% empty %}
    <li>No users associated with this ledger.</li>
    {% endfor %}
</ul>

<ul>
    {% for payment in payments %}
    <li>
        <a href="{% url 'Bill_2_split:PaymentDetailView' payment.pk ledger.pk user.pk %}"> {{ payment.name }} </a>
    </li>
    {% endfor %}
</ul>

<nav>
    <ul>
        <li>
            <a href="{% url 'Bill_2_split:PaymentAddView' ledger.pk user.pk %}">Add new payment</a>
        </li>
    </ul>
    <ul>
        <li>
            <a href="{% url 'Bill_2_split:LedgerEditView' ledger.pk user.pk %}"> Edit ledger</a>
        </li>
    </ul>
</nav>

{% endblock %}

Bill_2_split/Bill_2_split/templates/Bill_2_split/list_of_ledgers.html
{% extends 'Bill_2_split/_base.html' %}

{% block Bill_2_split_content %}
{% load static %}

<nav id="horni-nav">
    <ul><li><a href="{% url 'Bill_2_split:IndexView' %}">
            <img src="{% static 'Bill_2_split/icons/home_page.png' %}"><span>Homepage</span></a></li>
        <li><a href="{% url 'Bill_2_split:UserView' %}">
            <img src="{% static 'Bill_2_split/icons/user.png' %}"><span>User selection</span></a></li>
        <li><a href="{% url 'Bill_2_split:ListOfLedgersView' user.pk %}">
            <img src="{% static 'Bill_2_split/icons/ledgers.png' %}"><span>You are here</span></a></li>
        <li><a href=""><img src="{% static 'Bill_2_split/icons/bw_ledger.png' %}"></a></li>
        <li><a href=""><img src="{% static 'Bill_2_split/icons/bw_glass.png' %}"></a></li>
    </ul>
</nav>

<h1>
    Hello <strong>{{ user.name }} </strong>!
</h1>

<h3>
    This is the overview  of your ledgers
</h3>

<ul>
    {% for ledger in ledgers %}

    <li>

        <a href="{% url 'Bill_2_split:LedgerDetailView' ledger.pk user.pk %}"> {{ ledger.name }} </a>

    </li>

    {% endfor %}
</ul>

<nav>
    <ul>
        <li>
            <a href="{% url 'Bill_2_split:LedgerAddView' user.pk %}"> Add new ledger</a>
        </li>
    </ul>
</nav>
{% endblock %}

Bill_2_split/Bill_2_split/templates/Bill_2_split/payment_detail.html
{% extends 'Bill_2_split/_base.html' %}

{% block Bill_2_split_content %}
{% load static %}

<nav id="horni-nav">
    <ul>
    <li><a href="{% url 'Bill_2_split:IndexView' %}">
            <img src="{% static 'Bill_2_split/icons/home_page.png' %}"><span>Homepage</span></a></li>
    <li><a href="{% url 'Bill_2_split:UserView' %}">
            <img src="{% static 'Bill_2_split/icons/user.png' %}"><span>User selection</span></a></li>
    <li><a href="{% url 'Bill_2_split:ListOfLedgersView' user.pk %}">
            <img src="{% static 'Bill_2_split/icons/ledgers.png' %}"><span>Ledgers overview</span></a></li>
    <li><a href="{% url 'Bill_2_split:LedgerDetailView' ledger.pk user.pk %}">
            <img src="{% static 'Bill_2_split/icons/ledger.png' %}"><span>Ledger detail</span></a></li>
    <li><a href="#">
            <img src="{% static 'Bill_2_split/icons/glass.png' %}"><span>You are here</span></a></li>
    </ul>
</nav>

<h1>
    This is specific payment detail:
</h1>

<h2>{{ payment.name }}</h2>
<p>Ledger name: {{ payment.ledger.name }}</p>
<p>Entry created by: {{ payment.user.name }}</p>
<p>Date of entry creation: {{ payment.entry_time }}</p>
<p>Date of payment: {{ payment.payment_time }}</p>
<p>Amount paid: {{ payment.cost }}</p>


    {% for relation, balance_change in balance_change %}

        {% if relation.relation > 0 %}

                <p> This payment has been paid by {{ relation.user.name }} and the balance change due to this payment is: </p>
                <p> {{ relation.user.name }} +{{ balance_change }} </p>

        {% endif %}

    {% endfor %}

    {% for relation, balance_change in balance_change %}

        {% if relation.relation < 0 %}

                <p> {{ relation.user.name }}  {{ balance_change }} </p>

        {% endif %}

    {% endfor %}

<nav>
    <ul></ul>
    <ul>
        <li>
            <a href="{% url 'Bill_2_split:PaymentEditView' payment_pk=payment.pk ledger_pk=ledger.pk user_pk=user.pk %}"> Edit payment</a>
        </li>
    </ul>
</nav>

<nav>
    <ul></ul>
    <ul>
        <li>
            <form method="post" action="{% url 'Bill_2_split:PaymentDeleteView' payment_pk=payment.pk ledger_pk=ledger.pk user_pk=user.pk %}">
                {% csrf_token %}
                <button type="submit">Delete payment</button>
            </form>
        </li>

    </ul>
</nav>


{% endblock %}

Bill_2_split/Bill_2_split/templates/Bill_2_split/payment_edit.html
{% extends 'Bill_2_split/_base.html' %}

{% block Bill_2_split_content %}
{% load static %}

<nav id="horni-nav">
    <ul>
    <li><a href="{% url 'Bill_2_split:IndexView' %}">
            <img src="{% static 'Bill_2_split/icons/home_page.png' %}"><span>Homepage</span></a></li>
    <li><a href="{% url 'Bill_2_split:UserView' %}">
            <img src="{% static 'Bill_2_split/icons/user.png' %}"><span>User selection</span></a></li>
    <li><a href="{% url 'Bill_2_split:ListOfLedgersView' user.pk %}">
            <img src="{% static 'Bill_2_split/icons/ledgers.png' %}"><span>Ledgers overview</span></a></li>
    <li><a href="{% url 'Bill_2_split:LedgerDetailView' ledger.pk user.pk %}">
            <img src="{% static 'Bill_2_split/icons/ledger.png' %}"><span>Ledger detail</span></a></li>
    <li><a href="#">
            <img src="{% static 'Bill_2_split/icons/glass.png' %}"><span>You are here</span></a></li>
    </ul>
</nav>

<h3>Edit Payment for Ledger:</h3>
<h1>{{ ledger.name }}</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save changes</button>
</form>
{% endblock %}

Bill_2_split/Bill_2_split/templates/Bill_2_split/relation_add.html
{% extends 'Bill_2_split/_base.html' %}

{% block Bill_2_split_content %}
{% load static %}

<nav id="horni-nav">
    <ul>
    <li><a href="{% url 'Bill_2_split:IndexView' %}">
            <img src="{% static 'Bill_2_split/icons/home_page.png' %}"><span>Homepage</span></a></li>
    <li><a href="{% url 'Bill_2_split:UserView' %}">
            <img src="{% static 'Bill_2_split/icons/user.png' %}"><span>User selection</span></a></li>
    <li><a href="{% url 'Bill_2_split:ListOfLedgersView' user.pk %}">
            <img src="{% static 'Bill_2_split/icons/ledgers.png' %}"><span>Ledgers overview</span></a></li>
    <li><a href="{% url 'Bill_2_split:LedgerDetailView' ledger.pk user.pk %}">
            <img src="{% static 'Bill_2_split/icons/ledger.png' %}"><span>Ledger detail</span></a></li>
    <li><a href="#">
            <img src="{% static 'Bill_2_split/icons/glass.png' %}"><span>You are here</span></a></li>
    </ul>
</nav>

<h1>Detail Payment: {{ payment.name }}</h1>
<p>Cost: {{ payment.cost }}</p>
<p>Description: {{ payment.desc }}</p>

<h2>Ledger: {{ ledger.name }}</h2>
<p>Managed by: {{ user.username }}</p>

<form method="post">
    {% csrf_token %}

    <h2>Add Relations for Users</h2>

    {% for form in relation_forms %}
        <div>
            <h3>User: {{ form.instance.user.username }}</h3>
            {{ form.as_p }}
        </div>
    {% endfor %}

    <button type="submit">Add Relations</button>
</form>

{% endblock %}